# Generated by Django 5.0.1 on 2024-01-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YourModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(db_index=True, max_length=20, verbose_name='Timestamp')),
                ('turbidity', models.FloatField(verbose_name='Turbidity')),
                ('temperature', models.FloatField(verbose_name='Temperature')),
                ('pH', models.FloatField(verbose_name='pH')),
            ],
            options={
                'verbose_name': 'Your Model',
                'verbose_name_plural': 'Your Models',
            },
        ),
    ]
